alias grep="grep --color"
alias ls="ls --color=auto"
alias l="ls -l"
alias gst="git status"
alias gd="git diff"
alias gam="git commit -am"
alias detox="detox -s lower *"
alias tree="tree -C"
cdx() {cd $1; ls -l;}; alias cd="cdx"

alias setperformance="sudo cpupower frequency-set -g performance"
alias setpowersave="sudo cpupower frequency-set -g powersave"
alias backlight="sudo tee /sys/class/backlight/intel_backlight/brightness <<<"
alias meteo="curl http://wttr.in/"
alias temperature="curl http://v2.wttr.in/"
alias lf="find . -not -path '*/\.*' -type f"
alias remotefs="sshfs void.tic.sh:/srv/storage/ ~/storage"
alias voidpush="rsync --verbose --archive --delete -e 'ssh -p 2455' ~/storage void.tic.sh:/srv"
alias voidpull="rsync --verbose --archive --delete -e 'ssh -p 2455' void.tic.sh:/srv/storage ~"
alias hail="ls -hAil"
alias vim="nvim +NERDTree"
alias config="cd ~/repos/perso/dotfiles && nvim +NERDTree install.sh"
alias syncaur="pushd ~/repos/perso/dotfiles/ && ./syncaur.sh && popd"
alias blackarchsearch="pacman -Sgg | grep blackarch | cut -d' ' -f2 | sort -u | grep"
alias tmp="nvim ~/storage/private/TMP.txt"
alias todo="nvim ~/storage/private/TODO.txt"
alias toread="nvim ~/storage/private/TOREAD.txt"
alias towatch="nvim ~/storage/private/TOWATCH.txt"
alias cdsvpn="pushd ~/repos/cdiscount/docker-citrix && docker run --rm --privileged -it --network=host --env-file=config --name=citrix_vpn --volume=/etc/resolv.conf:/etc/resolv.conf docker-registry.cdweb.biz/sre/citrix:b4533cb"
alias screenshot='grim -g "$(slurp)" /tmp/$(date +screenshot-%s.png)'
#alias virsh="virsh --connect qemu:///system"
alias safeshutdown='voidpush && sudo pacman -Syu && shutdown now'
