alias ls="ls --color=auto"
alias l="ls -l"
alias gst="git status"
alias gd="git diff"
alias gam="git commit -am"

alias setperformance="sudo cpupower frequency-set -g performance"
alias setpowersave="sudo cpupower frequency-set -g powersave"
alias backlight="sudo tee /sys/class/backlight/intel_backlight/brightness <<<"
alias meteo="curl http://wttr.in/"
alias temperature="curl http://v2.wttr.in/"
alias lf="find . -not -path '*/\.*' -type f"
alias remotefs="sshfs void.tic.sh:/srv/storage/ ~/storage"
alias voidpush="rsync --verbose --archive --delete -e 'ssh -p 2455' ~/storage void.tic.sh:/srv"
alias voidpull="rsync --verbose --archive --delete -e 'ssh -p 2455' void.tic.sh:/srv/storage ~"
alias hail="ls -hAil"
alias vim="nvim +NERDTree"
alias config="cd ~/repos/perso/dotfiles && nvim +NERDTree install.sh"
alias syncaur="pushd ~/repos/perso/dotfiles/ && ./syncaur.sh && popd"
alias blackarchsearch="pacman -Sgg | grep blackarch | cut -d' ' -f2 | sort -u | grep"
#alias virsh="virsh --connect qemu:///system"
