alias ls="ls --color=auto"
alias l="ls -l"

alias setperformance="sudo cpupower frequency-set -g performance"
alias setpowersave="sudo cpupower frequency-set -g powersave"
alias hma="sudo /usr/local/bin/hma-vpn.sh"
alias backlight="sudo tee /sys/class/backlight/intel_backlight/brightness <<<"
alias meteo="curl http://wttr.in/"
alias temperature="curl http://v2.wttr.in/"
alias lf="find . -not -path '*/\.*' -type f"
alias remotefs="sshfs void.tic.sh:/srv/storage/ ~/storage"
alias voidpush="rsync --verbose --archive --delete -e 'ssh -p 2455' ~/storage void.tic.sh:/srv"
alias voidpull="rsync --verbose --archive --delete -e 'ssh -p 2455' void.tic.sh:/srv/storage ~"
alias hail="ls -hAil"
alias vim="nvim +NERDTree"
alias config="pushd ~/repos/perso/dotfiles && nvim +NERDTree install.sh && popd"
alias syncaur="pushd ~/repos/perso/dotfiles/ && ./syncaur.sh && popd"
#alias virsh="virsh --connect qemu:///system"
